version: '3'

services:
  prometheus:
    image: prom/prometheus
    user: "0:0"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-storage:/prometheus
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    restart: unless-stopped

  python:
    build: ./python-app
    volumes:
      - ./python-app:/app
    ports:
      - "8000:8000"
    command: ["./start.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  grafana-storage: {}
  prometheus-storage: {}