version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    environment:
      - TZ=Europe/Paris
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
    restart: always

  python:
    build: ./python-app
    volumes:
      - ./python-app:/app
    ports:
      - "8000:8000"
    command: ["./start.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"